export const SAVE_BACKGROUND_COLOR = "SAVE_BACKGROUND_COLOR";
export const SAVE_TRANSFORM = "SAVE_TRANSFORM";
export const SAVE_TRANSFORM_ORIGIN = "SAVE_TRANSFORM_ORIGIN";
export const INIT = "INIT";
